server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eaza?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 320982

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml